// src/routes/browserprivacy/+page.svelte
<script>
	import Button from '../../components/Button.svelte';
	import ProjectPage from '../../components/projects/ProjectPage.svelte';
	import Section from '../../components/Section.svelte';
</script>

<svelte:head>
	<title>Privacy policies for browser extensions - Bennett Hollstein</title>
	<meta name="description" content="Crafting powerful websites and web applications" />
	<meta name="robots" content="noindex" />
</svelte:head>

<ProjectPage>
	<Section title="Privacy policies">
		<h1 class="text-xl font-bold">Privacy policies for browser extensions</h1>
		<p>Please select a browser extension</p>

		<div class="flex flex-col gap-4">
			<a href="/browserprivacy/skip-silence">
				<Button highlighted>Skip Silence</Button>
			</a>
			<a href="/browserprivacy/dontbugme">
				<Button highlighted>Don't Bug Me</Button>
			</a>
			<a href="/browserprivacy/bangs">
				<Button highlighted>Bangs for Google</Button>
			</a>
		</div>
	</Section>
</ProjectPage>

// src/pages/browserprivacy/index.tsx
import { Link } from "gatsby";
import React from "react";
import Layout from "../../components/layout/Layout";
import Button from "../../components/various/Button";
import PageCard from "../../components/various/PageCard";

function Index() {
  return (
    <Layout>
      <PageCard>
        <h1 className="font-bold text-3xl">
          Privacy policies for browser extensions
        </h1>
        <p>Please select a browser extension</p>

        <div className="flex flex-col gap-6">
          <Link to="/browserprivacy/dontbugme">
            <Button highlighted>DontBugMe</Button>
          </Link>
          <Link to="/browserprivacy/skip-silence">
            <Button highlighted>Skip Silence</Button>
          </Link>
          <Link to="/browserprivacy/bangs">
            <Button highlighted>Bangs for Google</Button>
          </Link>
        </div>
      </PageCard>
    </Layout>
  );
}

export default Index;
