// src/components/landing/Hero.tsx
import React from "react";
import uisGrid from "../../images/uis-grid.png";
import logo from "../../images/logo.svg";
import HeroBackground from "./HeroBackground";
import ThreeLogo from "./ThreeLogo";
import Balancer from "react-wrap-balancer";

function Hero() {
  return (
    <section
      className="min-h-[90vh] w-full flex items-center justify-center text-center relative"
      id="top"
    >
      <HeroBackground />

      <div className="flex flex-col">
        <ThreeLogo />
        <h1 className="font-bold text-brand-700 text-4xl lg:text-6xl md:max-w-4xl z-10 p-6 mix-blend-overlay">
          <Balancer>Crafting beautiful websites and web applications</Balancer>
        </h1>
      </div>
    </section>
  );
}

export default Hero;

// src/components/landing/Hero.svelte
<script>
	import ColorfulBackground from './ColorfulBackground.svelte';
</script>

<section class="w-full relative overflow-hidden">
	<div class="absolute top-0 left-0 mix-blend-multiply w-full">
		<ColorfulBackground />
	</div>
	<h1
		class="text-4xl md:text-6xl font-bold text-center z-10 absolute top-0 left-0 w-full h-full flex items-center"
	>
		Crafting powerful websites and web applications
	</h1>
</section>

<style>
	h1 {
		background-color: white;
		color: black;
		mix-blend-mode: screen;
	}

	section {
		min-height: 75vh;
	}
</style>
