// src/components/project-card.tsx
import Image, { StaticImageData } from "next/image";
import Link from "next/link";
import { cn } from "@/lib/utils";
import { TagList } from "./project/tag-list";

export type ProjectCardProps = {
  title: string;
  description: string;
  image: StaticImageData;
  href: string;
  /**
   * `screenshot` bleeds the image off the right edge of the card,
   * `icon` centers a small logo.
   */
  variant?: "screenshot" | "icon";
  imageClassName?: string;
  tags?: string[];
};

export function ProjectCard({
  title,
  description,
  image,
  href,
  variant = "screenshot",
  imageClassName,
  tags = [],
}: ProjectCardProps) {
  return (
    <Link
      href={href}
      className="group flex w-72 shrink-0 snap-start flex-col sm:w-80 md:w-96"
    >
      <div
        className={cn(
          "flex aspect-9/12 items-center overflow-hidden rounded-4xl bg-neutral-100",
          variant === "screenshot" ? "justify-end" : "justify-center",
        )}
      >
        <Image
          src={image}
          alt={title}
          className={cn(
            "transition-transform duration-300 group-hover:scale-[1.02]",
            variant === "screenshot" && "h-3/4 w-3/4 rounded-l-xl object-cover",
            variant === "icon" && "w-1/3 object-contain",
            imageClassName,
          )}
        />
      </div>

      <div className="mt-2 font-medium">
        <h3>{title}</h3>
        <p className="text-neutral-400">{description}</p>
      </div>

      <TagList tags={tags} />
    </Link>
  );
}

// src/components/landing/ProjectCard.svelte
<script>
	export let image = '';
	export let size = 2;
	export let color = '#FFFFFF';
	export let preTitle = '';
	export let title = '';
	export let href = '';
</script>

<a
	{href}
	class="card rounded-lg shadow-brand p-5 relative hover:scale-105 transition-all duration-500"
	style="--size: {size};--color: {color};"
>
	<img src={image} alt="" style:--tag={title} class="rounded object-cover w-full h-full" />

	<div class="absolute top-0 left-0 w-full h-full">
		<div
			class="w-full h-full card-gradient rounded-lg flex justify-end items-center text-white text-center flex-col p-4"
		>
			<p class="font-bold text-xs">
				{preTitle}
			</p>
			<h3 class="font-bold text-2xl">
				{title}
			</h3>
		</div>
	</div>
</a>

<style>
	.card {
		grid-column: span var(--size);
		background-color: var(--color);
	}

	.card-gradient {
		background: linear-gradient(
			180deg,
			rgba(0, 0, 0, 0) 0%,
			rgba(0, 0, 0, 0) 50%,
			rgba(0, 0, 0, 0.8) 100%
		);
	}
</style>
