// src/routes/legal/impressum/+page.svelte
<script>
	import ProjectPage from '../../../components/projects/ProjectPage.svelte';
	import Section from '../../../components/Section.svelte';
</script>

<svelte:head>
	<title>Impressum - Bennett Hollstein</title>
	<meta name="description" content="Crafting powerful websites and web applications" />
	<meta name="robots" content="noindex" />
</svelte:head>

<ProjectPage>
	<Section title="Impressum">
		<p>
			Bennett Hollstein
			<br />
			Reinbeckstr. 4-8, Apartement 322
			<br />
			12459 Berlin
		</p>
		<h4>Kontakt</h4>
		<p>E-Mail: properly+webseite@pm.me</p>
		<h4>Haftung für Inhalte</h4>

		<p>
			Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den
			allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch
			nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder
			nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen.
		</p>

		<p>
			Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den
			allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab
			dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von
			entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.
		</p>

		<h4>Haftung für Links</h4>

		<p>
			Unser Angebot enthält Links zu externen Websites Dritter, auf deren Inhalte wir keinen
			Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für
			die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten
			verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche
			Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht
			erkennbar.
		</p>

		<p>
			Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete
			Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen
			werden wir derartige Links umgehend entfernen.
		</p>

		<h4>Urheberrecht</h4>

		<p>
			Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem
			deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der
			Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des
			jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den
			privaten, nicht kommerziellen Gebrauch gestattet.
		</p>

		<p>
			Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die
			Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet.
			Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen
			entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte
			umgehend entfernen.
		</p>
		<p>
			Quelle: <a href="https://www.e-recht24.de">e-recht24.de</a>
		</p>
	</Section>
</ProjectPage>

// src/pages/impressum.tsx
import React from "react";
import Layout from "../components/layout/Layout";
import PageCard from "../components/various/PageCard";
import Helmet from "react-helmet";

function Impressum() {
  return (
    <Layout>
      <PageCard>
        <Helmet>
          <title>Impressum - Hollstein</title>
          <meta name="robots" content="noindex nofollow" />
        </Helmet>
        <h1 className="font-bold text-3xl">Impressum</h1>
        <h4>Angaben gemäß § 5 TMG</h4>
        <p>
          Bennett Hollstein
          <br />
          Reinbeckstr. 4-8, Apartement 322
          <br />
          12459 Berlin
        </p>
        <h4>Kontakt</h4>
        <p>E-Mail: properly+webseite@pm.me</p>
        <h4>Haftung für Inhalte</h4>{" "}
        <p>
          Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte
          auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach
          §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht
          verpflichtet, übermittelte oder gespeicherte fremde Informationen zu
          überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige
          Tätigkeit hinweisen.
        </p>{" "}
        <p>
          Verpflichtungen zur Entfernung oder Sperrung der Nutzung von
          Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt.
          Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der
          Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden
          von entsprechenden Rechtsverletzungen werden wir diese Inhalte
          umgehend entfernen.
        </p>{" "}
        <h4>Haftung für Links</h4>{" "}
        <p>
          Unser Angebot enthält Links zu externen Websites Dritter, auf deren
          Inhalte wir keinen Einfluss haben. Deshalb können wir für diese
          fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der
          verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der
          Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der
          Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige
          Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar.
        </p>{" "}
        <p>
          Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch
          ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei
          Bekanntwerden von Rechtsverletzungen werden wir derartige Links
          umgehend entfernen.
        </p>{" "}
        <h4>Urheberrecht</h4>{" "}
        <p>
          Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen
          Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung,
          Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der
          Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des
          jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite
          sind nur für den privaten, nicht kommerziellen Gebrauch gestattet.
        </p>{" "}
        <p>
          Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt
          wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden
          Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf
          eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen
          entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen
          werden wir derartige Inhalte umgehend entfernen.
        </p>
        <p>
          Quelle: <a href="https://www.e-recht24.de">e-recht24.de</a>
        </p>
      </PageCard>
    </Layout>
  );
}

export default Impressum;
